### ISSUE TITLE
Question .obj file

### ISSUE THREAD

**Issue by taeyeopl** [THU-DA-6D-Pose-Group/Self6D-Diff-Renderer#1]
Thanks for sharing good work. 

Could you share full version of .obj file??
I got empty information from here.

https://github.com/THU-DA-6D-Pose-Group/Self6D-Diff-Renderer/blob/00c82e83a34eb65c135e530a852a510792198bca/core/dr_utils/dr_utils.py#L40

**Comment by AGI-Mkz** [comment]
i have same question, have you found it ?

**Comment by taeyeopl** [comment]
not yet !

**Comment by zhongcl-thu** [comment]
i have same question too.

**Comment by GalenOOO** [comment]
Install "git lfs"
Then run 'git lfs pull' in the shell. The .obj will be downloaded.
