### ISSUE TITLE
How the Average Recall is calculated?

### ISSUE THREAD

**Issue by acmff22** [THU-DA-6D-Pose-Group/Self6D-Diff-Renderer#2]
Thanks for sharing your great work!!!
In your paper, you present the results for the Average Recall of ADD metric, I wonder how the AP calculated？ And what differences between the average precision and average recall in this case?

**Comment by wangg12** [comment]
Hi @acmff22 , I use https://github.com/thodan/bop_toolkit to calculate the metrics, where Average Recall is used to report the results. 

The difference of AR and AP can be found here (https://en.wikipedia.org/wiki/Precision_and_recall).
Apparently, AR is more suitable than AP to know how well the model detects an object.
<img width="327" alt="image" src="https://user-images.githubusercontent.com/9958446/98342316-3d6b2480-204b-11eb-9739-99604f0e5111.png">
