### ISSUE TITLE
How to define the false negative samples in LINEMOD?

### ISSUE THREAD

**Issue by acmff22** [THU-DA-6D-Pose-Group/Self6D-Diff-Renderer#3]
Thanks for your answer in last issue. 
I'm still confused about the average recall.  For the tests images in each object sequence, they are all positive samples, because the model is supposed to detect the object pose in each image correctly, How to define the false negative? 
And can you share cropped LINEMOD dataset for evaluation?
Thanks!!!

**Comment by wangg12** [comment]
If you assume all images in a sequence are positive samples, then you are using a "human detector". In this case, there is no false negative sample. But if you use a model to detect (or determine) whether an object is in an image, it is not true.

Cropped LineMOD dataset was introduced in Bousmalis et al., Unsupervisedpixel-level domain adaptation with generative adversarial networks. CVPR 2017. You can download it from http://download.tensorflow.org/data/cropped_linemod.tar.gz
