### ISSUE TITLE
Question about the zoom-in

### ISSUE THREAD

**Issue by rcao-hk** [THU-DA-6D-Pose-Group/Self6D-Diff-Renderer#4]
Hi,

Thanks for your excellent work! Here I have a question. I noticed here is a 'zoom-in' operation in the figure of your paper. However, there is no implementation in your repo. So, could you introduce the method you used for changing ROI?

Regards,
Rui

**Comment by wangg12** [comment]
There is no "zoom-in" operation used in this work. The input image is the original image, we just show the "zoomed-in part" for better visualization.
