### ISSUE TITLE
How to prepare customized object models

### ISSUE THREAD

**Issue by DaoyiG** [THU-DA-6D-Pose-Group/Self6D-Diff-Renderer#9]
Hi!

Thanks for sharing this renderer! 

I would like to render my customized object models which come already in .obj format (Wavefront) with texture. To add color information on each vertex I use "Filters/Color Creation and Processing/Ambient Occlusion" in MeshLab, and this will indeed make each vertex contains the RGB information, e.g. ```v -0.016006 0.029566 0.032946 0.964706 0.964706 0.964706``` However, the object in the rendered images still seems to have no color and it's basically purely in white. So I wonder what I should do to solve this issue. 

Thanks!

**Comment by wangg12** [comment]
Because the color of your model is nearly white: `0.964706 0.964706 0.964706`. You need to assign the actual color for the `.obj` file.

**Comment by DaoyiG** [comment]
Thanks! Problem solved!
